version: '3.8'

services:
  sql-db:
    image: postgres:15.2
    container_name: best_travel
    restart: always
    volumes:
      - ./db/sql/create_schema.sql:/docker-entrypoint-initdb.d/create_schema.sql
      - ./db/sql/data.sql:/docker-entrypoint-initdb.d/data.sql
    environment:
      - POSTGRES_DB=${SPRING_DATASOURCE_DB}
      - POSTGRES_USER=${SPRING_DATASOURCE_USERNAME}
      - POSTGRES_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    ports:
      - "5432:5432"

  cache-db:
    image: redis:6.2-alpine
    container_name: best_travel_cache
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --loglevel warning --requirepass 1234

  document-db:
    image: mongo:6.0.4
    restart: always
    container_name: best_travel_users
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${SPRING_MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${SPRING_MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${SPRING_MONGO_DATABASE}
    ports:
      - "27017:27017"
    volumes:
      - ./db/mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro